### ISSUE TITLE
20.5.1 Pipes

### ISSUE THREAD

**Issue by ASmithOWL** [rust-lang/rust-by-example#1439]
I followed the example in Rust By Example Section 20.5.1 (Pipes) precisely, and I'm getting the following error (posted at the bottom as well w full stack backtrace)

thread 'main' panicked at 'couldn't spawn wc: The system cannot find the file specified. (os error 2)', rust_pipes.rs:21:17
stack backtrace:

```
use std::io::prelude::*;
use std::process::{Command, Stdio};

static PANGRAM: &'static str =
"the quick brown fox jumped over the lazy dog\n";

fn main() {
    // Spawn the wc command
    let process = match Command::new("wc")
                            .stdin(Stdio::piped())
                            .stdout(Stdio::piped())
                            .spawn() {
    Err(why) => panic!("couldn't spawn wc: {}", why),
    Ok(process) => process,
    };


    // write a string to the stdin of wc
    // 
    // stdin has type Option<ChildStdin> but since we know the instance
    // must have one we can directly unwrap it
    match process.stdin.unwrap().write_all(PANGRAM.as_bytes()) {
        Err(why) => panic!("Couldn't write to wc stdin: {}", why),
        Ok(_) => println!("sent pangram to wc"),
    }

    // Because stdin does not live after the above calls it is `drop`ped,
    // and the pipe is closed.
    //
    // This is very important, otherwise wc wouldn't start processing the
    // input we just sent

    // The stdout field also has type Option<ChildStdout> so must be unwrapped.
    let mut s = String::new();
    match process.stdout.unwrap().read_to_string(&mut s) {
        Err(why) => panic!("Couldn't read wc stdout: {}", why),
        Ok(_) => print!("wc responded with :\n{}", s),
    }
}


```
```
thread 'main' panicked at 'couldn't spawn wc: The system cannot find the file specified. (os error 2)', rust_pipes.rs:21:17
stack backtrace:

 0:     0x7ff784f154fe - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98   
   1:     0x7ff784f154fe - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66       
   2:     0x7ff784f154fe - std::sys_common::backtrace::_print_fmt
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\sys_common\backtrace.rs:67
   3:     0x7ff784f154fe - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\sys_common\backtrace.rs:46
   4:     0x7ff784f28aab - core::fmt::write
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\fmt\mod.rs:1096
   5:     0x7ff784f12578 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\io\mod.rs:1568
   6:     0x7ff784f1810d - std::sys_common::backtrace::_print
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\sys_common\backtrace.rs:49
   7:     0x7ff784f1810d - std::sys_common::backtrace::print
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\sys_common\backtrace.rs:36
   8:     0x7ff784f1810d - std::panicking::default_hook::{{closure}}
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:208
   9:     0x7ff784f17bd9 - std::panicking::default_hook
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:225
  10:     0x7ff784f189c0 - std::panicking::rust_panic_with_hook
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:591
  11:     0x7ff784f184f1 - std::panicking::begin_panic_handler::{{closure}}
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:497
  12:     0x7ff784f15e8f - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\sys_common\backtrace.rs:141
  13:     0x7ff784f18449 - std::panicking::begin_panic_handler
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:493
  14:     0x7ff784f183fc - std::panicking::begin_panic_fmt
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:435
  15:     0x7ff784f02cba - <alloc::raw_vec::RawVec<T,A> as core::ops::drop::Drop>::drop::hfa6b7267e1e76552
  16:     0x7ff784f06686 - core::ops::function::FnOnce::call_once::h33cc28b596e84c1c
  17:     0x7ff784f074e7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3f126b52544fd9a2
  18:     0x7ff784f0408c - std::rt::lang_start::{{closure}}::h52053780b4cb50bc
  19:     0x7ff784f18b57 - core::ops::function::impls::{{impl}}::call_once
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\library\core\src\ops\function.rs:280
  20:     0x7ff784f18b57 - std::panicking::try::do_call
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:379
  21:     0x7ff784f18b57 - std::panicking::try
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:343
  22:     0x7ff784f18b57 - std::panic::catch_unwind
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panic.rs:431
  23:     0x7ff784f18b57 - std::rt::lang_start_internal
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\rt.rs:51
  24:     0x7ff784f04064 - std::rt::lang_start::hfa456dfaf02d7f68
  25:     0x7ff784f03320 - main
  26:     0x7ff784f2cdc8 - invoke_main
                               at D:\a01\_work\26\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  27:     0x7ff784f2cdc8 - __scrt_common_main_seh
                               at D:\a01\_work\26\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  28:     0x7ff8c2dd7034 - BaseThreadInitThunk
  29:     0x7ff8c3ee2651 - RtlUserThreadStart
```

**Comment by balroggg** [comment]
@ASmithOWL I think you just don't have `wc` command on Windows.

Maybe we need rewrite this example from
`echo "..." | wc` to something cross platform
`dir .`
or use `cfg!(target_os)` guard.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
